import {
  readFileSync,
  readdirSync,
  writeFileSync,
  mkdirSync,
} from "node:fs";

const filledDirectory = readdirSync("./icons/filled");
const regularDirectory = readdirSync("./icons/regular");

const filledIcons = filledDirectory.map((file) => {
  const iconName = file.replace(".svg", "");
  const svgContent = readFileSync(`./icons/filled/${file}`, "utf-8");

  return { name: iconName, svg: svgContent };
});

const regularIcons = regularDirectory.map((file) => {
  const iconName = file.replace(".svg", "");
  const svgContent = readFileSync(`./icons/regular/${file}`, "utf-8");

  return { name: iconName, svg: svgContent };
});

const iconsPluginBlock = `// !! This file is auto-generated by the build-icons.mjs script. Do not edit this file directly. !!
// !! To update the icons, run 'pnpm build:icons' in the foundation-tailwind package. !!

import plugin from "tailwindcss/plugin";
import type { CSSRuleObject } from "tailwindcss/types/config";

export const iconsPlugin = plugin(function ({ addUtilities }) {
  const filledIcons = ${JSON.stringify(filledIcons, null, 2)};
  const regularIcons = ${JSON.stringify(regularIcons, null, 2)};

  const iconComponents = {} as CSSRuleObject;

  filledIcons.forEach((icon) => {
    iconComponents[\`.icon-filled-\${icon.name}\`] = {
      '--svg': \`url("data:image/svg+xml;utf8,\${icon.svg.replace(/"/g, "'").replace(/</g, "%3C").replace(/>/g, "%3E")}")\`,
    };
  });

  regularIcons.forEach((icon) => {
    iconComponents[\`.icon-regular-\${icon.name}\`] = {
      '--svg': \`url("data:image/svg+xml;utf8,\${icon.svg.replace(/"/g, "'").replace(/</g, "%3C").replace(/>/g, "%3E")}")\`,
    };
  });

  addUtilities(iconComponents);
});
`;

const iconsTypesBlock = `// !! This file is auto-generated by the build-icons.mjs script. Do not edit this file directly. !!
// !! To update the icons, run 'pnpm build:icons' in the foundation-tailwind package. !!

export type TTailwindRegularIconPrefix = "icon-regular";
export type TTailwindFilledIconPrefix = "icon-filled";

export type TTailwindRegularIconValue = ${regularIcons.map((icon) => `"${icon.name}"`).join(" | ")};
export type TTailwindFilledIconValue = ${filledIcons.map((icon) => `"${icon.name}"`).join(" | ")};

export type TTailwindRegularIconClass = \`\${TTailwindRegularIconPrefix}-\${TTailwindRegularIconValue}\`;
export type TTailwindFilledIconClass = \`\${TTailwindFilledIconPrefix}-\${TTailwindFilledIconValue}\`;

export type TTailwindIconClass = TTailwindRegularIconClass | TTailwindFilledIconClass;
`;

mkdirSync("./src/preset/plugins", {
  recursive: true,
});
mkdirSync("./src/classes", {
  recursive: true,
});
writeFileSync("./src/preset/plugins/icons.generated.ts", iconsPluginBlock);
writeFileSync("./src/classes/icons.generated.ts", iconsTypesBlock);
console.log(
  `Wrote ./src/preset/plugins/icons.generated.ts and ./src/classes/icons.generated.ts with ${filledIcons.length} filled icons and ${regularIcons.length} regular icons.`,
);
