// !! This file is auto-generated by the build-typography.mjs script. Do not edit this file directly. !!
// !! To update the icons, run 'pnpm build:typography' in the foundation-tailwind package. !!

import plugin from 'tailwindcss/plugin';

export const typographyPlugin = plugin(function ({ addUtilities }) {
  addUtilities({
  ".text-body-large": {
    "font": "var(--typography-body-large-font)",
    "letterSpacing": "var(--typography-body-large-letter-spacing)"
  },
  ".text-body-medium": {
    "font": "var(--typography-body-medium-font)",
    "letterSpacing": "var(--typography-body-medium-letter-spacing)"
  },
  ".text-body-small": {
    "font": "var(--typography-body-small-font)",
    "letterSpacing": "var(--typography-body-small-letter-spacing)"
  },
  ".text-caption-large": {
    "font": "var(--typography-caption-large-font)",
    "letterSpacing": "var(--typography-caption-large-letter-spacing)"
  },
  ".text-caption-medium": {
    "font": "var(--typography-caption-medium-font)",
    "letterSpacing": "var(--typography-caption-medium-letter-spacing)"
  },
  ".text-caption-small": {
    "font": "var(--typography-caption-small-font)",
    "letterSpacing": "var(--typography-caption-small-letter-spacing)"
  },
  ".text-display-large": {
    "font": "var(--typography-display-large-font)",
    "letterSpacing": "var(--typography-display-large-letter-spacing)"
  },
  ".text-display-medium": {
    "font": "var(--typography-display-medium-font)",
    "letterSpacing": "var(--typography-display-medium-letter-spacing)"
  },
  ".text-display-small": {
    "font": "var(--typography-display-small-font)",
    "letterSpacing": "var(--typography-display-small-letter-spacing)"
  },
  ".text-heading-large": {
    "font": "var(--typography-heading-large-font)",
    "letterSpacing": "var(--typography-heading-large-letter-spacing)"
  },
  ".text-heading-medium": {
    "font": "var(--typography-heading-medium-font)",
    "letterSpacing": "var(--typography-heading-medium-letter-spacing)"
  },
  ".text-heading-small": {
    "font": "var(--typography-heading-small-font)",
    "letterSpacing": "var(--typography-heading-small-letter-spacing)"
  },
  ".text-label-large": {
    "font": "var(--typography-label-large-font)",
    "letterSpacing": "var(--typography-label-large-letter-spacing)"
  },
  ".text-label-medium": {
    "font": "var(--typography-label-medium-font)",
    "letterSpacing": "var(--typography-label-medium-letter-spacing)"
  },
  ".text-label-small": {
    "font": "var(--typography-label-small-font)",
    "letterSpacing": "var(--typography-label-small-letter-spacing)"
  },
  ".text-title-large": {
    "font": "var(--typography-title-large-font)",
    "letterSpacing": "var(--typography-title-large-letter-spacing)"
  },
  ".text-title-medium": {
    "font": "var(--typography-title-medium-font)",
    "letterSpacing": "var(--typography-title-medium-letter-spacing)"
  },
  ".text-title-small": {
    "font": "var(--typography-title-small-font)",
    "letterSpacing": "var(--typography-title-small-letter-spacing)"
  }
});
})
