/**
 * The prefix for the Tailwind background classes.
 */
export type TTailwindBgPrefix = 'bg';

/**
 * The possible values for the Tailwind background classes.
 */
export type TTailwindBgValue =
  | 'none'
  | 'common-backdrop'
  | 'common-heavy-divider'
  | 'common-navigation-bar'
  | 'common-scrim'
  | 'common-shadow'
  | 'common-shimmer'
  | 'over-media-0'
  | 'over-media-100'
  | 'over-media-200'
  | 'over-media-300'
  | 'selection-start'
  | 'selection-end'
  | 'shift-100'
  | 'shift-200'
  | 'shift-300'
  | 'shift-400'
  | 'state-hover'
  | 'state-idle'
  | 'state-press'
  | 'surface-0'
  | 'surface-100'
  | 'surface-200'
  | 'surface-300'
  | 'system-alert'
  | 'system-contrast'
  | 'system-emphasis'
  | 'system-neutral'
  | 'system-success'
  | 'system-warning'
  | 'inverse-none'
  | 'inverse-common-backdrop'
  | 'inverse-common-heavy-divider'
  | 'inverse-common-navigation-bar'
  | 'inverse-common-scrim'
  | 'inverse-common-shadow'
  | 'inverse-common-shimmer'
  | 'inverse-over-media-0'
  | 'inverse-over-media-100'
  | 'inverse-over-media-200'
  | 'inverse-over-media-300'
  | 'inverse-selection-start'
  | 'inverse-selection-end'
  | 'inverse-shift-100'
  | 'inverse-shift-200'
  | 'inverse-shift-300'
  | 'inverse-shift-400'
  | 'inverse-state-hover'
  | 'inverse-state-idle'
  | 'inverse-state-press'
  | 'inverse-surface-0'
  | 'inverse-surface-100'
  | 'inverse-surface-200'
  | 'inverse-surface-300'
  | 'inverse-system-alert'
  | 'inverse-system-contrast'
  | 'inverse-system-emphasis'
  | 'inverse-system-neutral'
  | 'inverse-system-success'
  | 'inverse-system-warning'
  | 'action-alert'
  | 'action-emphasis'
  | 'action-link'
  | 'action-over-media'
  | 'action-soft-emphasis'
  | 'action-standard'
  | 'action-sub-emphasis'
  | 'action-subtle'
  | 'action-utility'
  | 'inverse-action-alert'
  | 'inverse-action-emphasis'
  | 'inverse-action-link'
  | 'inverse-action-over-media'
  | 'inverse-action-soft-emphasis'
  | 'inverse-action-standard'
  | 'inverse-action-sub-emphasis'
  | 'inverse-action-subtle'
  | 'inverse-action-utility';

/**
 * The complete Tailwind background class type, which combines the prefix and value.
 */
export type TTailwindBgClass = `${TTailwindBgPrefix}-${TTailwindBgValue}`;
