export type TTailwindBgPrefix = "bg";

export type TTailwindBgValue =
  | "none"
  | "common-backdrop"
  | "common-heavy-divider"
  | "common-navigation-bar"
  | "common-scrim"
  | "common-shadow"
  | "common-shimmer"
  | "content-default"
  | "content-emphasis"
  | "content-link"
  | "content-muted"
  | "over-media-0"
  | "over-media-100"
  | "over-media-200"
  | "over-media-300"
  | "selection-start"
  | "selection-end"
  | "shift-100"
  | "shift-200"
  | "shift-300"
  | "shift-400"
  | "state-hover"
  | "state-idle"
  | "state-press"
  | "stroke-default"
  | "stroke-emphasis"
  | "stroke-muted"
  | "surface-0"
  | "surface-100"
  | "surface-200"
  | "surface-300"
  | "system-alert"
  | "system-contrast"
  | "system-emphasis"
  | "system-neutral"
  | "system-success"
  | "system-warning"
  | "action-alert"
  | "action-emphasis"
  | "action-link"
  | "action-over-media"
  | "action-soft-emphasis"
  | "action-standard"
  | "action-sub-emphasis"
  | "action-subtle"
  | "action-utility";

export type TTailwindBgClass = `${TTailwindBgPrefix}-${TTailwindBgValue}`;
