// !! This file is auto-generated by the build-typography.mjs script. Do not edit this file directly. !!
// !! To update the icons, run 'pnpm build:typography' in the foundation-tailwind package. !!
export type TTailwindTextBodyPrefix = 'text-body';
export type TTailwindTextCaptionPrefix = 'text-caption';
export type TTailwindTextDisplayPrefix = 'text-display';
export type TTailwindTextHeadingPrefix = 'text-heading';
export type TTailwindTextLabelPrefix = 'text-label';
export type TTailwindTextTitlePrefix = 'text-title';

export type TTailwindTextValue =
  | 'small'
  | 'medium'
  | 'large';

export type TTailwindTextBodyClass = `${TTailwindTextBodyPrefix}-${TTailwindTextValue}`;
export type TTailwindTextCaptionClass = `${TTailwindTextCaptionPrefix}-${TTailwindTextValue}`;
export type TTailwindTextDisplayClass = `${TTailwindTextDisplayPrefix}-${TTailwindTextValue}`;
export type TTailwindTextHeadingClass = `${TTailwindTextHeadingPrefix}-${TTailwindTextValue}`;
export type TTailwindTextLabelClass = `${TTailwindTextLabelPrefix}-${TTailwindTextValue}`;
export type TTailwindTextTitleClass = `${TTailwindTextTitlePrefix}-${TTailwindTextValue}`;

export type TTailwindTextClass =
  TTailwindTextBodyClass | 
  TTailwindTextCaptionClass | 
  TTailwindTextDisplayClass | 
  TTailwindTextHeadingClass | 
  TTailwindTextLabelClass | 
  TTailwindTextTitleClass;
