import type { PresetsConfig } from "tailwindcss/types/config";

import {
  BREAKPOINTS,
  CONTENT_COLORS,
  BG_COLORS,
  BORDER_COLORS,
  RADIUS,
  TEXT_ALIGN,
  VERTICAL_ALIGN,
  STROKE,
  GAP,
  PADDING,
  MARGIN,
  SIZE,
} from "./preset/constants";

import { utilitiesPlugin } from "./preset/plugins/utilities";
import { typographyPlugin } from "./preset/plugins/typography";
import { iconsPlugin } from "./preset/plugins/icons.generated";

export default {
  darkMode: "media",
  corePlugins: {
    content: false,
    textColor: false, // content replaces textColor
    flexWrap: false,
    overflow: false,
    borderRadius: false,
    textOverflow: false,
    borderWidth: false,
    borderColor: false,
    textAlign: false,
    verticalAlign: false,
    preflight: false,
    fontFamily: false,
    boxShadow: false,
    zIndex: false,
    transform: false,
    rotate: false,
    translate: false,
    scale: false,
    transformOrigin: false,
    gridColumn: false,
    gridRow: false,
    gridTemplateColumns: false,
    gridTemplateRows: false,
    objectFit: false,
    objectPosition: false,
    listStyleType: false,
    listStyleImage: false,
    listStylePosition: false,
    tableLayout: false,
    resize: false,
    touchAction: false,
    overscrollBehavior: false,
    appearance: false,
    backdropBlur: false,
    backdropFilter: false,
    boxSizing: false,
    animation: false,
    lineClamp: false,
    ringWidth: false,
    ringColor: false,
    ringOpacity: false,
    ringOffsetWidth: false,
    ringOffsetColor: false,
    blur: false,
    brightness: false,
    contrast: false,
    dropShadow: false,
    grayscale: false,
    hueRotate: false,
    invert: false,
    saturate: false,
    sepia: false,
    filter: false,
    contain: false,
    backdropBrightness: false,
    backdropContrast: false,
    backdropGrayscale: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
    gradientColorStops: false,
    scrollSnapType: false,
    borderSpacing: false,
    fontVariantNumeric: false,
  },
  theme: {
    screens: {
      small: `${BREAKPOINTS.xsmall + 1}px`,
      medium: `${BREAKPOINTS.small + 1}px`,
      large: `${BREAKPOINTS.medium + 1}px`,
      xlarge: `${BREAKPOINTS.large + 1}px`,
    },

    colors: CONTENT_COLORS,
    backgroundColor: BG_COLORS,
    borderColor: BORDER_COLORS,
    borderRadius: RADIUS,

    textAlign: TEXT_ALIGN,
    verticalAlign: VERTICAL_ALIGN,
    borderWidth: STROKE,

    extend: {
      // Adds 1:1, 16:9, 2:1, 4:3, 4:5, and 5:4
      aspectRatio: {
        "1-1": "1 / 1",
        "16-9": "16 / 9",
        "2-1": "2 / 1",
        "4-3": "4 / 3",
        "4-5": "4 / 5",
        "5-4": "5 / 4",
      },

      gap: GAP,
      padding: PADDING,
      margin: MARGIN,
      width: SIZE,
      height: SIZE,
      minWidth: SIZE,
      maxWidth: SIZE,
      minHeight: SIZE,
      maxHeight: SIZE,
    },
  },
  plugins: [utilitiesPlugin, typographyPlugin, iconsPlugin],
} as PresetsConfig;
